---
title: "Modeling"
output: html_document
---

```{r, echo = FALSE}
# Loading in packages
library(tidyverse)
library(gt)
library(MASS)

# Loading in the data
NY <- read_csv("NY_AIRBNB.csv")

# Creating a themeing function, so we don't have to keep typing out our themes
regression_theme <- function() {
  theme_bw() +
    theme(
      plot.title = element_text(size = 18,
                                face = "bold",
                                hjust = .5),
      axis.title = element_text(size = 15,
                                face = "bold",
                                hjust = .5),
      legend.title = element_text(size = 15,
                                  face = "bold"),
      plot.subtitle = element_text(size = 16,
                                   face = "italic",
                                   hjust = .5)
    )
}
```


## Data Cleaning
```{r, fig.height = 6, fig.width = 6}
# Clean version of data with selected variables
NY_clean <- NY |> 
  # We are predicting price, so no NAs
  filter(!is.na(price)) |> 
  # Selecting desired variables
  dplyr::select(price, host_is_superhost, last_scraped, host_since,
         calculated_host_listings_count, neighbourhood_group_cleansed,
         room_type, accommodates, bathrooms, bedrooms,
         beds, minimum_nights, number_of_reviews, review_scores_rating) |> 
  # Removing any other NAs
  na.omit() |> 
  # Turning price into a numeric variable
  mutate(price = round(as.numeric(gsub("[$,]", "", price)), 2),
         # finding number of days the host has been a host
         days_since_host_joined = as.numeric(last_scraped - host_since)) |> 
  # Getting rid of Shared Room and Hotel Room due to low observations
  filter(room_type %in% c("Entire home/apt", "Private room")) |> 
  # deselecting the dates
  dplyr::select(!c(host_since, last_scraped)) |> 
  # Filtering for prices between $50 and $500
  filter(price >= 50,
         price <= 500)

# Transformations of natural logs
NY_transformed <- NY_clean |> 
  mutate(lnPRICE = log(price),
         lnHOST_LISTINGS = log(calculated_host_listings_count + 1),
         lnMINIMUM_NIGHTS = log(minimum_nights + 1),
         lnREVIEWS = log(number_of_reviews + 1))
```

<br>

## Visuals
### LOG Transformations
```{r, fig.height = 6, fig.width = 6}
# Histogram of Price before and after log transformation
NY_transformed |> 
  ggplot(aes(x = price)) +
  geom_histogram(fill = "steelblue", col = "black") +
  labs(title = "Price: Before LOG Transformation",
       x = "Price",
       y = "Count",
       subtitle = "Graph displays distribution before 5000 sample") +
  regression_theme()

# Prices AFTER LOG
NY_transformed |> 
  ggplot(aes(x = log(price))) +
  geom_histogram(fill = "steelblue", col = "black") +
  labs(title = "Price: After LOG Transformation",
       x = "LOG(Price)",
       y = "Count",
      subtitle = "Graph displays distribution before 5000 sample") +
  regression_theme()
```

### Data Table
```{r}
# Example data for modeling
NY_clean |> 
  dplyr::select(price, accommodates, beds, bedrooms, bathrooms, neighbourhood_group_cleansed, room_type) |> 
  slice_head(n = 3) |> 
  gt() |> 
  gtExtras::gt_theme_espn() |> 
  gtsave("Exampledata.png")
```

### Correlation Table
```{r}
# Correlations
## Note: make sure to run model_data in the next code chunk first
cors <- round(cor(model_data[ , c("accommodates", "bathrooms",
                                      "bedrooms", "beds", "lnMINIMUM_NIGHTS", "lnHOST_LISTINGS", "lnREVIEWS", 
                                      "review_scores_rating", "days_since_host_joined", "lnPRICE")]),3)[10, ]

# Putting correlations in a df
correlations <- data.frame(Variable = names(cors), Correlation = as.numeric(cors))

# Making a gt table of correlations
correlations |> 
  filter(Variable != "lnPRICE") |> 
  gt() |> 
  tab_header(title = md("**Correlations with lnPRICE**")) |> 
  gtsave("Correlations.png")

# Scatterplot matrix
pairs(~  accommodates + bathrooms + bedrooms + beds + review_scores_rating + days_since_host_joined + lnHOST_LISTINGS + lnMINIMUM_NIGHTS + lnREVIEWS + lnPRICE, data = model_data, upper.panel = NULL, gap = 0)
```

<br>

# Modeling

## Modeling Setup
```{r}
# Removing vars from the model to only have ln vars
model_data <- NY_transformed |> 
  dplyr::select(!c(price, number_of_reviews, calculated_host_listings_count, minimum_nights)) |> 
  filter(bathrooms < 10)

# Sampling 5000 rows
set.seed(412)
model_data <- model_data[sample(nrow(model_data), 5000, replace = FALSE), ]

summary(model_data)
str(model_data)
```

## Full Model
```{r}
model_full <- lm(lnPRICE ~ ., data = model_data)
summary(model_full)
```

## Forward Selection using BIC
```{r, fig.height = 4, fig.width = 6}
# Null Model
model_null <- lm(lnPRICE ~ 1, data = model_data)

# Correlation matrix
pairs(~  accommodates + bathrooms + bedrooms + beds + review_scores_rating + days_since_host_joined + lnHOST_LISTINGS + lnMINIMUM_NIGHTS + lnREVIEWS + lnPRICE, data = model_data, upper.panel = NULL, gap = 0)

# Forward Selection with BIC as comparison
stepAIC(model_null, 
        # goes from null model to full model
        scope = list(lower = model_null, upper = model_full), 
        # k = log(nrow(model_data)) --> BIC (constant in the BIC formula)
        k = log(nrow(model_data)), 
        # Forward selection
        direction = "forward")

# Forward and Backward Selection
model_complete <- lm(formula = lnPRICE ~ accommodates + neighbourhood_group_cleansed + 
                               lnMINIMUM_NIGHTS + room_type + lnHOST_LISTINGS + bedrooms + 
                               review_scores_rating + host_is_superhost + bathrooms + days_since_host_joined, 
                             data = model_data)

summary(model_complete)
plot(model_complete)
```

## Simple Model
```{r, fig.height = 4, fig.width = 6}
# Simple model
model_simple <- lm(lnPRICE ~ accommodates + neighbourhood_group_cleansed + bedrooms + lnMINIMUM_NIGHTS, data = model_data)

plot(model_simple)
summary(model_simple)
```

<br>

# Analysis
## Residuals vs. Response Variable lnPRICE
```{r, fig.height = 4, fig.width = 6}
# Resisduals vs. lnPRICE
# Complete Model
model_data |> 
  ggplot(aes(x = lnPRICE, y = model_complete$residuals)) +
  geom_point() +
  regression_theme() +
  labs(x = "LOG(Price)",
       y = "Complete Model Residuals")

# Simple Model
model_data |> 
  ggplot(aes(x = lnPRICE, y = model_simple$residuals)) +
  geom_point() +
  regression_theme() +
  labs(x = "LOG(Price)",
       y = "Simple Model Residuals")
```

## Collinearity
```{r}
# Using the VIF function from the car package to minimize time to find VIF for each var
library(car)

# Complete model
vif(model_complete)

# Simple model
vif(model_simple)
```

